name: Compile Hermes Engine

on:
  workflow_dispatch

jobs:
  build-windows:
    runs-on: "windows-2019"

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '16.5'
      - name: Compile Hermesc for Windows
        run: |
          choco install ninja
          cmake -S . -B build -G 'Visual Studio 16 2019' -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build --config Release --target hermesc
      - uses: actions/upload-artifact@v3
        name: Upload Windows Binaries
        with:
          name: hermesc-windows
          path: build/bin/Release/hermesc.exe

  build-linux:
    runs-on: "ubuntu-latest"

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/checkout@v2
      - name: Compile Hermesc for Linux
        run: |
          sudo apt update
          sudo apt install cmake git ninja-build libicu-dev python2 zip libreadline-dev
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build --config Release --target hermesc
      - uses: actions/upload-artifact@v3
        name: Upload Linux Binaries
        with:
          name: hermesc-linux
          path: build/bin/hermesc
  
  build-mac:
    runs-on: "macos-latest"

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/checkout@v2
      - name: Compile Hermesc for MacOS
        run: |  
          brew install cmake git ninja
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build ./build --config Release --target hermesc
      - uses: actions/upload-artifact@v3
        name: Upload MacOS Binaries
        with:
          name: hermesc-mac
          path: build/bin/hermesc
          
  package:
    runs-on: "ubuntu-latest"
    needs: [build-windows, build-linux, build-mac]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: hermesc-linux
          path: ~/artifacts/linux64-bin
          
      - uses: actions/download-artifact@v3
        with:
          name: hermesc-mac
          path: ~/artifacts/osx-bin

      - uses: actions/download-artifact@v3
        with:
          name: hermesc-windows
          path: ~/artifacts/win64-bin
      
      - uses: actions/upload-artifact@v3
        name: Upload Hermesc Package
        with:
          name: hermesc-package
          path: ~/artifacts
